comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: false
  branches:
    - main

fixes:
  - "^go-faiss/::"

ignore:
  - "LICENSES"
  - ".git"
  - "*.yml"
  - "*.md"
  - "docs/.*"
  - "**/gpu/*.go"

coverage:
  precision: 2
  round: down
  range: "0...80"

  status:
    project:
      default:
        target: 60%
        threshold: 0%
    patch:
      default:
        target: 50%
        threshold: 0%
        if_ci_failed: error
