name: "Code Check"

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  ut:
    name: "Code check with faiss ${{ matrix.faiss_version }}"
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        faiss_version: [v1.7.3, main]
    env:
      os: ubuntu
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: go-faiss
      - name: Checkout faiss
        uses: actions/checkout@v3
        with:
          repository: facebookresearch/faiss
          path: faiss
          ref: ${{ matrix.faiss_version }}
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.19.3'
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install libopenblas-dev
      - name: Build faiss and install
        run: |
          mkdir -p ${{ github.workspace }}/faiss/build
          cd ${{ github.workspace }}/faiss/build
          cmake -DFAISS_ENABLE_GPU=OFF \
                -DFAISS_ENABLE_PYTHON=OFF \
                -DBUILD_TESTING=OFF \
                -DFAISS_ENABLE_C_API=ON \
                -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/dest \
                ..
          make -j $(nproc)
          make install
          cp -fr ${{ github.workspace }}/faiss/build/c_api/*.a ${{ github.workspace }}/dest/lib/
      - name: Setup CGO flags for go
        run: |
          go env -w CGO_CFLAGS="-I${{ github.workspace }}/dest/include $(go env CGO_CFLAGS)"
          go env -w CGO_LDFLAGS="-L${{ github.workspace }}/dest/lib $(go env CGO_LDFLAGS)"
      - name: Build and test for go-faiss
        run: |
          cd go-faiss
          go build ./...
          go test ./...
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50.1
          working-directory: ${{ github.workspace }}/go-faiss
      - name: Run coverage
        if: ${{ matrix.faiss_version == 'v1.7.3' }}
        run: |
          cd go-faiss
          go test -race -coverprofile=coverage.txt -covermode=atomic ./...
      - name: Upload coverage to Codecov
        if: ${{ matrix.faiss_version == 'v1.7.3' }}
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          files: ./go-faiss/coverage.txt
          verbose: true
          fail_ci_if_error: true

